spring:
  application:
    name: CourseSchedule
  profiles:
    active: dev
---
server:
  port: 8080
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://sh-cynosdbmysql-grp-eauf5d9w.sql.tencentcdb.com:20694/project?useSSL=true&useServerPrepStmts=true&autoReconnect=true&useUnicode=true
    username: root
    password: ItcvRpV@l0
  config:
    activate:
      on-profile: dev
logging:
  level:
    root: info
---
server:
  port: 8888
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/schedule?useServerPrepStmts=true&autoReconnect=true&useUnicode=true
    username: schedule
    password: y5STyBARH8eX8y7M
  config:
    activate:
      on-profile: prod
logging:
  level:
    root: info